version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 32
  
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: 3.8
      PYTHON_ARCH: 32
      
    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: 3.8
      PYTHON_ARCH: 64
      
init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
install:
- cmd: >-
    set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    
    python --version

    python -m pip install --upgrade pip
    
    python -m pip install -r requirements.txt

build:
  verbosity: minimal
test_script:
- cmd: .\local_install.cmd
artifacts:
- path: result/
  name: results
- path: dist/*.whl
  name: wheels
- path: keywords/keywords.html
  name: keywords.html
- path: keywords/keywords.xml
  name: keywords.xml
deploy_script:
  - ps: |
      if($env:APPVEYOR_REPO_TAG -eq 'true') {
        Write-Output ("Deploying " + $env:APPVEYOR_REPO_TAG_NAME + " to PyPI...")

        python -m pip install twine

        python -m twine upload -u ${Env:USER} -p ${Env:PASS} --skip-existing dist/*.whl

      } else {
        Write-Output "No tag for deployment"
      }
on_finish:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\result\xunit.xml))   